import itertools
from typing import List, Tuple


def generate_brute_candidates(settings):
    """
    Generate all possible combinations of characters from the charset
    for lengths ranging from min_length to max_length.
    """
    charset = settings["charset"]
    min_length = settings["min"]
    max_length = settings["max"]
    
    count = 0
    for length in range(min_length, max_length + 1):
        for combo in itertools.product(charset, repeat=length):
            count += 1
            yield "".join(combo).encode()
    # print(f"Generated {count} candidates for charset: '{charset}', min_length: {min_length}, max_length: {max_length}")


def yield_brute_batches(generator, batch_size):
    batch = []
    total_batches = 0
    for candidate in generator:
        batch.append(candidate)
        if len(batch) >= batch_size:
            total_batches += 1
            yield batch
            batch = []
    if batch:
        total_batches += 1
        yield batch
    # print(f"Total batches generated: {total_batches}")


def get_brute_count(settings):
    """
    Calculate the number of possible passwords generated by brute-force.
    """
    charset = settings["charset"]
    min_length = settings["min"]
    max_length = settings["max"]
    
    total_count = 0
    for length in range(min_length, max_length + 1):
        total_count += len(charset) ** length
    return total_count


def build_length_table(min_length: int, max_length: int, charset_length: int) -> List[Tuple[int, int, int]]:
    """
    Build a table of (length, start_index, end_index) for global index mapping.
    """
    table = []
    start = 0
    for length in range(min_length, max_length + 1):
        count = charset_length ** length
        end = start + count
        table.append((length, start, end))
        start = end
    return table


def index_to_candidate(index: int, charset: bytes, length: int) -> bytes:
    """
    Map an index to a candidate using base-N encoding (N = len(charset)).
    """
    if length <= 0:
        return b""
    base = len(charset)
    chars = []
    value = index
    for _ in range(length):
        value, rem = divmod(value, base)
        chars.append(charset[rem:rem + 1])
    chars.reverse()
    return b"".join(chars)


def index_to_brut_candidate(index: int, charset: bytes, length_table: List[Tuple[int, int, int]]) -> bytes:
    """
    Map a global index to the correct length bucket and candidate bytes.
    """
    for length, start, end in length_table:
        if start <= index < end:
            local_index = index - start
            return index_to_candidate(local_index, charset, length)
    raise IndexError("Index out of range for brute-force search space.")
